services:
  www:
    build:
      context: .
      dockerfile: Dockerfile.ReactJS1
    ports:
      - "3000:80" # Map localhost:3000 to container's port 80
    restart: always
    depends_on:
      - mysql

  login:
    build:
      context: .
      dockerfile: Dockerfile.ReactJS2
    ports:
      - "3001:80" # Map localhost:3000 to container's port 80
    restart: always
    depends_on:
      - mysql

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.FastAPI
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    env_file:
      - backend/.env
    environment:
      MYSQL_ROOT_PASSWORD: ItemRaj@1562
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
